// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wygqrfduttlrtgrnfbiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5Z3FyZmR1dHRscnRncm5mYml3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1Njk0NDMsImV4cCI6MjA2NTE0NTQ0M30.6c8U7rw_5lAS_oIL26O5M5G12ejN9OOvGV13SVUrFm0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);